### ISSUE TITLE
Memory leakage in wow_simulator

### ISSUE THREAD

**Issue by sub-1337** [wowcube/wasm#5]
If wow_simulator is launched with pacman dll the memory is leaking. Need futher investigation.

**Comment by sub-1337** [comment]
![image](https://user-images.githubusercontent.com/11762109/105910174-a4401e80-6039-11eb-88d1-ba4f91d36fda.png)

**Comment by sub-1337** [comment]
It looks like the leakage exist on some point of time passing by, when initialization is made.

**Comment by sub-1337** [comment]
In rubic it does not reproduce, probably some function call specific to pacman.

**Comment by sub-1337** [comment]
![image](https://user-images.githubusercontent.com/11762109/105914841-f421e400-603f-11eb-8eab-06467ee8b982.png)
It's DrawBitmap call that are leaking.

**Comment by sub-1337** [comment]
It's `m_buff` that are not being pop'ed in wrong lunch options situation, I thing we should add check on it's size and function draw call skipping.

**Comment by araud** [comment]
Fixed
